routes:
  /:
    controller: channel
    template: index
    # rss: true
    # filter:

  # /recommend/:
  #   # controller: channel
  #   # filter: tag:recommended
  #   template: recommend
  #   rss: false
    

collections:
  # /:
  #   template: home

  /es/:
    template: index
    permalink: /es/{slug}/
    filter: tag:es+tag:-en+tag:-br
    # order: published_at.asc
    data: tag.es
    # rss: true

  /en/:
    template: index
    permalink: /en/{slug}/
    filter: tag:en+tag:-es+tag:-br
    # order: published_at/.asc
    data: tag.en
    # rss: true

  /br/:
    template: index
    permalink: /br/{slug}/
    filter: tag:br+tag:-es+tag:-en
    # order: published_at.asc
    data: tag.br
    # rss: true


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/




