#!/usr/bin/env node
/**
 * Download the theme's webfonts and generate their @font-face rules.
 *
 * The theme used to load Inter and Roboto Mono from fonts.googleapis.com on every
 * page view, which meant two extra hosts, two TLS handshakes and a render-blocking
 * stylesheet in front of the first paint. The fonts are small enough to live in the
 * theme, so they do — this script is how they got there, and how they get updated.
 *
 * Run manually when a font needs a version bump:  node scripts/sync-fonts.mjs
 *
 * It asks Google's CSS API for the same families the theme used, keeps the latin and
 * latin-ext subsets (latin-ext is what Spanish accents need), downloads the woff2
 * files into assets/fonts/, and writes assets/css/fonts.css with the @font-face rules
 * and their unicode-ranges so a browser still only fetches the subset it needs.
 *
 * Fonts are shipped under their own licences: Inter is SIL OFL 1.1, Roboto Mono is
 * Apache 2.0. Both licence texts are downloaded next to the files.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

// The families, and the subsets worth shipping. `latin-ext` carries the accented
// characters Spanish content needs; the Cyrillic/Greek/Vietnamese subsets are dropped.
const FAMILIES = [
  {
    request: "Inter:opsz,wght@14..32,400..700",
    name: "Inter",
    slug: "inter",
    license: {
      file: "LICENSE-Inter.txt",
      url: "https://raw.githubusercontent.com/rsms/inter/master/LICENSE.txt",
    },
  },
  {
    request: "Roboto+Mono:wght@400..700",
    name: "Roboto Mono",
    slug: "roboto-mono",
    license: {
      file: "LICENSE-Roboto-Mono.txt",
      url: "https://raw.githubusercontent.com/googlefonts/RobotoMono/main/OFL.txt",
    },
  },
];

const SUBSETS = ["latin", "latin-ext"];
const FONTS_DIR = "assets/fonts";
const CSS_OUT = "assets/css/fonts.css";

/** Google's stylesheet puts every subset in its own block, with a `/* subset *​/` label. */
function parseSubsets(css) {
  const blocks = [];
  const pattern = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g;
  for (const match of css.matchAll(pattern)) {
    const [, label, body] = match;
    const read = (property) =>
      body.match(new RegExp(`${property}:\\s*([^;]+);`))?.[1].trim() ?? "";
    const src = read("src");
    const url = src.match(/url\(([^)]+)\)/)?.[1]?.replace(/['"]/g, "");
    if (!url) continue;
    blocks.push({
      subset: label,
      url,
      family: read("font-family").replace(/['"]/g, ""),
      style: read("font-style"),
      weight: read("font-weight"),
      range: read("unicode-range"),
    });
  }
  return blocks;
}

async function fetchText(url) {
  const response = await fetch(url, { headers: { "User-Agent": UA } });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`);
  return response.text();
}

async function fetchBinary(url) {
  const response = await fetch(url, { headers: { "User-Agent": UA } });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`);
  return Buffer.from(await response.arrayBuffer());
}

const rules = [];
mkdirSync(FONTS_DIR, { recursive: true });

for (const family of FAMILIES) {
  const css = await fetchText(
    `https://fonts.googleapis.com/css2?family=${family.request}&display=swap`,
  );
  const blocks = parseSubsets(css);
  if (blocks.length === 0) throw new Error(`no @font-face blocks found for ${family.name}`);

  for (const subset of SUBSETS) {
    const block = blocks.find((candidate) => candidate.subset === subset);
    if (!block) throw new Error(`no ${subset} subset for ${family.name}`);

    const local = `${family.slug}-${subset}.woff2`;
    const bytes = await fetchBinary(block.url);
    writeFileSync(join(FONTS_DIR, local), bytes);
    console.log(
      `  ${local.padEnd(28)} ${String(Math.round(bytes.length / 1024)).padStart(4)} kB  (${block.weight})`,
    );

    rules.push(
      [
        "@font-face {",
        `  font-family: "${family.name}";`,
        `  font-style: ${block.style};`,
        `  font-weight: ${block.weight};`,
        "  font-display: swap;",
        `  src: url("../fonts/${local}") format("woff2");`,
        `  unicode-range: ${block.range};`,
        "}",
      ].join("\n"),
    );
  }

  const license = await fetchText(family.license.url);
  writeFileSync(join(FONTS_DIR, family.license.file), license);
  console.log(`  ${family.license.file.padEnd(28)}    licence text`);
}

writeFileSync(
  CSS_OUT,
  [
    "/* Generated by scripts/sync-fonts.mjs — do not edit by hand.",
    "   Self-hosted so the theme makes no third-party requests. */",
    "",
    rules.join("\n\n"),
    "",
  ].join("\n"),
);
console.log(`\nwrote ${CSS_OUT} with ${rules.length} @font-face rules`);
