#!/usr/bin/env node
/**
 * Generate partials/icon.hbs — inline SVG icons — from upstream icon sets.
 *
 * The theme used to load Font Awesome's whole stylesheet (about 100 kB plus webfont
 * files) from a third-party CDN to render roughly twenty glyphs. Inline SVG is smaller,
 * needs no extra request, needs no font to finish loading before the icon appears, and
 * inherits colour through `currentColor`.
 *
 * Run manually when an icon needs to change:  node scripts/sync-icons.mjs
 *
 * Sources: Simple Icons (CC0 1.0) for brand marks, Bootstrap Icons (MIT) for the UI
 * glyphs. Licence texts are written to assets/licenses/. Sizes are set by the caller
 * through `class`, defaulting to 1em square.
 */
import { mkdirSync, writeFileSync } from "node:fs";

const SIMPLE_ICONS = "https://cdn.jsdelivr.net/npm/simple-icons@13.21.0/icons";
const BOOTSTRAP_ICONS = "https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/icons";

const LICENSES = [
  { file: "bootstrap-icons-LICENSE", url: "https://raw.githubusercontent.com/twbs/icons/main/LICENSE" },
  { file: "simple-icons-LICENSE", url: "https://cdn.jsdelivr.net/npm/simple-icons@13.21.0/LICENSE.md" },
];

/**
 * name -> source. The names are the theme's own, so call sites read as what they mean
 * rather than as which icon set they happen to come from.
 */
const ICONS = {
  // Brands (Simple Icons, CC0). `twitter` maps to the X mark: the platform renamed and
  // the old bird is not in the set any more.
  mastodon: `${SIMPLE_ICONS}/mastodon.svg`,
  linkedin: `${SIMPLE_ICONS}/linkedin.svg`,
  facebook: `${SIMPLE_ICONS}/facebook.svg`,
  youtube: `${SIMPLE_ICONS}/youtube.svg`,
  twitter: `${SIMPLE_ICONS}/x.svg`,
  tiktok: `${SIMPLE_ICONS}/tiktok.svg`,
  threads: `${SIMPLE_ICONS}/threads.svg`,
  instagram: `${SIMPLE_ICONS}/instagram.svg`,
  bluesky: `${SIMPLE_ICONS}/bluesky.svg`,
  whatsapp: `${SIMPLE_ICONS}/whatsapp.svg`,
  reddit: `${SIMPLE_ICONS}/reddit.svg`,
  x: `${SIMPLE_ICONS}/x.svg`,

  // UI (Bootstrap Icons, MIT).
  clock: `${BOOTSTRAP_ICONS}/clock.svg`,
  link: `${BOOTSTRAP_ICONS}/link-45deg.svg`,
  "location-dot": `${BOOTSTRAP_ICONS}/geo-alt.svg`,
  user: `${BOOTSTRAP_ICONS}/person.svg`,
  search: `${BOOTSTRAP_ICONS}/search.svg`,
  close: `${BOOTSTRAP_ICONS}/x-lg.svg`,
  envelope: `${BOOTSTRAP_ICONS}/envelope.svg`,
  menu: `${BOOTSTRAP_ICONS}/list.svg`,
};

/** Reduce an SVG file to the parts an inline icon needs: the viewBox and the shapes. */
function toInline(svg, name, first) {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`${name}: no viewBox`);

  const body = [...svg.matchAll(/<(path|circle|rect|polygon|polyline|line|ellipse)\b([^>]*?)\/?>/g)]
    .map((match) => {
      const attributes = match[2]
        .replace(/\s(fill|stroke)="(?!currentColor)[^"]*"/g, "")
        .replace(/\s+/g, " ")
        .trim();
      return `<${match[1]} ${attributes}/>`;
    })
    .join("");
  if (!body) throw new Error(`${name}: no shapes`);

  return (
    `{{${first ? "#" : "else "}match name "=" "${name}"}}<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" ` +
    `fill="currentColor" class="inline-block align-[-0.125em] {{#if class}}{{class}}{{else}}w-4 h-4{{/if}}" aria-hidden="true" ` +
    `focusable="false">${body}</svg>`
  );
}

async function fetchText(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} for ${url}`);
  return response.text();
}

const branches = [];
for (const [name, url] of Object.entries(ICONS)) {
  branches.push(toInline(await fetchText(url), name, branches.length === 0));
  console.log(`  ${name}`);
}

// assets/, not docs/: docs/ is excluded from the theme package, and the MIT licence
// for these icons has to travel with the icons themselves.
mkdirSync("assets/licenses", { recursive: true });
for (const entry of LICENSES) {
  writeFileSync("assets/licenses/" + entry.file + ".md", await fetchText(entry.url));
  console.log(`  ${entry.file}.md`);
}

writeFileSync(
  "partials/icon.hbs",
  [
    "{{!-- Generated by scripts/sync-icons.mjs — do not edit by hand.",
    "     Inline SVG so the theme needs no icon font: brand marks from Simple Icons",
    "     (CC0 1.0), UI glyphs from Bootstrap Icons (MIT, see assets/licenses/).",
    "",
    '     Usage: {{> "icon" name="clock" class="w-3 h-3 mr-1"}}',
    "     `class` defaults to w-4 h-4; colour follows currentColor. --}}",
    ...branches,
    "{{else}}",
    "{{! Unknown name: render nothing rather than a broken glyph. }}",
    "{{/match}}",
    "",
  ].join("\n"),
);
console.log(`\nwrote partials/icon.hbs with ${branches.length} icons`);
