name: deploy-theme
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read 
jobs: 
  deploy:
    if: ${{ github.event_name == 'push' && github.actor == 'ngeorger' || github.event_name == 'workflow_dispatch' && github.actor == 'ngeorger' }}
    runs-on: ubuntu-latest
    steps:
      - 
        name: Harden Runner
        uses: step-security/harden-runner@v2 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        name: Checkout Repository
      
      - name: Deploy Ghost Theme to website
        uses: sredevopsorg/action-deploy-theme@68d7b0f98e20212068a39ea90c0f84ce4ab770a8 # v1.7.3  
        continue-on-error: false
        with:
          api-url: ${{ secrets.GHOST_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          exclude: "node_modules gulpfile.js yarn.lock .gitignore .github .git LICENSE README.md .pre-commit-config.yaml routes.yaml tailwind.config.js"

