name: stale repo identifier

on:
#  push:
#  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '3 2 1 * *'

jobs:
  build:
    name: stale repo identifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Run stale_repos tool
      uses: docker://ghcr.io/github/stale_repos:v1@sha256:fb34ad6da139c145b82951dc06f7662adbcf07f06e525572a2099c89b278adfa
      env:
        GH_TOKEN: ${{ secrets.GHCR_PASS }}
        ORGANIZATION: sredevopsdev
        INACTIVE_DAYS: 100

    - name: Create issue
      uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # v5.0.1
      with:
        title: Stale repository report
        content-filepath: ./stale_repos.md
        assignees: ${{ secrets.GHCR_USER }}
        
