# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: tests-pr

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        # node-version: [14.x, 16.x, 18.x]
        node-version: [22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: ./yarn.lock

    - name: Install and test with ${{ matrix.node-version }}
      continue-on-error: true
      id: install
      run: |
          yarn install
          yarn build
          yarn run test:dev

    - name: Install if previous step failed
      if: steps.install.outcome == 'failure'
      run: |
        yarn install
        yarn build
        npx gscan . --verbose
