name: deploy-theme
on:
  workflow_run:
    workflows: ["tests"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        name: Checkout Repository
      
      - name: Deploy Ghost Theme to website
        uses: TryGhost/action-deploy-theme@a0ee1147d15641db25681e54549c4db9a53c2629 # v1.6.6
        continue-on-error: false
        with:
          api-url: ${{ secrets.SREDEVOPS_API_URL }}
          api-key: ${{ secrets.SREDEVOPS_ADMIN_API_KEY }}
          exclude: "node_modules gulpfile.js yarn.lock .gitignore .github .git LICENSE README.md"

